### ISSUE TITLE
Error: Index was out of range

### ISSUE THREAD

**Issue by ahmedkeskin** [ahmedkeskin/WaterWC#2]
When the click right button on the icon in the system tray, an error occurs.  If List<> objects are null, it could be.

**Error Message**

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
> Parameter name: index
>    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
>    at System.Collections.Generic.List`1.get_Item(Int32 index)
>    at WaterWCGUI.frmMain.systemTrayMenu_Opening(Object sender, CancelEventArgs e)
>    at System.Windows.Forms.ToolStripDropDown.OnOpening(CancelEventArgs e)
>    at System.Windows.Forms.ToolStripDropDown.SetVisibleCore(Boolean visible)
>    at System.Windows.Forms.ContextMenuStrip.SetVisibleCore(Boolean visible)
>    at System.Windows.Forms.ToolStripDropDown.Show(Int32 x, Int32 y)
>    at System.Windows.Forms.ContextMenuStrip.ShowInTaskbar(Int32 x, Int32 y)
>    at System.Windows.Forms.NotifyIcon.ShowContextMenu()
>    at System.Windows.Forms.NotifyIcon.WndProc(Message& msg)
>    at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> WaterWCGUI
>     Assembly Version: 1.0.0.0
>     Win32 Version: 1.0.0.0
>     CodeBase: file:///C:/Users/Necmeddin%20Keskin/Desktop/WaterWC/WaterWCGUI.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3353.0 built by: NET472REL1LAST_B
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
>

**Comment by ahmedkeskin** [comment]
Fixed
